export * from './wedding-authentication.service';
import { WeddingAuthenticationService } from './wedding-authentication.service';
export * from './wedding-configuration.service';
import { WeddingConfigurationService } from './wedding-configuration.service';
export * from './wedding-guests.service';
import { WeddingGuestsService } from './wedding-guests.service';
export * from './wedding-health.service';
import { WeddingHealthService } from './wedding-health.service';
export * from './wedding-rsvp.service';
import { WeddingRsvpService } from './wedding-rsvp.service';
export const APIS = [WeddingAuthenticationService, WeddingConfigurationService, WeddingGuestsService, WeddingHealthService, WeddingRsvpService];
