export * from './wedding-authentication.service';
import { WeddingAuthenticationService } from './wedding-authentication.service';
export * from './wedding-configuration.service';
import { WeddingConfigurationService } from './wedding-configuration.service';
export * from './wedding-couple.service';
import { WeddingCoupleService } from './wedding-couple.service';
export * from './wedding-health.service';
import { WeddingHealthService } from './wedding-health.service';
export * from './wedding-rsvp.service';
import { WeddingRsvpService } from './wedding-rsvp.service';
export * from './wedding-user-profile.service';
import { WeddingUserProfileService } from './wedding-user-profile.service';
export * from './wedding-users.service';
import { WeddingUsersService } from './wedding-users.service';
export const APIS = [WeddingAuthenticationService, WeddingConfigurationService, WeddingCoupleService, WeddingHealthService, WeddingRsvpService, WeddingUserProfileService, WeddingUsersService];
