#!/usr/bin/env node
/**
 * Regenerates src/environments/release.ts with the current git commit hash, so it can be embedded
 * as the Sentry `release` value (hub ADR-0026 / T253).
 *
 * Chained into `pnpm build` / `pnpm build:prod` (see package.json) so every production build
 * carries the exact commit it was built from. The committed file is a placeholder ('dev') between
 * builds — that's what `pnpm typecheck` / `pnpm lint` / `pnpm test` see, since none of them invoke
 * this script — so it's never "unknown"/undefined at build time, only possibly stale in a clean
 * checkout that hasn't been built yet.
 */

import { execSync } from 'node:child_process';
import { writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const outFile = path.join(repoRoot, 'src/environments/release.ts');

let hash = 'unknown';
try {
  hash = execSync('git rev-parse HEAD', { cwd: repoRoot, encoding: 'utf8' }).trim();
} catch (err) {
  console.warn(`generate-release: could not resolve the git commit hash, falling back to 'unknown': ${err.message}`);
}

const contents = `// AUTO-GENERATED by scripts/generate-release.mjs — regenerated on every \`pnpm build\` /
// \`pnpm build:prod\` run from the current git commit hash (hub ADR-0026 / T253). Do not hand-edit;
// any manual edit is overwritten on the next build. Committed with a 'dev' placeholder so
// typecheck/lint/test — which don't invoke the build — always have a real file to import.
export const RELEASE = '${hash}';
`;

writeFileSync(outFile, contents);
console.log(`generate-release: wrote RELEASE = '${hash}' to ${path.relative(repoRoot, outFile)}`);
