/**
 * Wedding API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AudienceListResponseDtoItemsInner { 
    id: AudienceListResponseDtoItemsInner.IdEnum;
    size: number;
    reachableSize: number;
}
export namespace AudienceListResponseDtoItemsInner {
    export const IdEnum = {
        ALL: 'all',
        NOT_REPLIED: 'not-replied',
        ATTENDING: 'attending',
        ATTENDING_NO_MENU: 'attending-no-menu'
    } as const;
    export type IdEnum = typeof IdEnum[keyof typeof IdEnum];
}


