/**
 * Wedding API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AudienceListResponseDtoItemsInner } from './audience-list-response-dto-items-inner';


export interface AudienceListResponseDto { 
    items: Array<AudienceListResponseDtoItemsInner>;
}

