/**
 * Wedding API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AuthTokenDto { 
    /**
     * JWT access token. Payload contains AppJwtClaims (sub, role). See AppJwtClaimsDto schema for token structure.
     */
    accessToken: string;
    tokenType: string;
    /**
     * Lifetime of the access token in seconds
     */
    expiresIn: number;
}

