/**
 * Wedding API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CreateWeddingConfigDtoVenuesInner } from './create-wedding-config-dto-venues-inner';
import { CreateWeddingConfigDtoLanguage } from './create-wedding-config-dto-language';
import { CreateWeddingConfigDtoDietaryPreferencesInner } from './create-wedding-config-dto-dietary-preferences-inner';
import { CreateWeddingConfigDtoMenusInner } from './create-wedding-config-dto-menus-inner';
import { CreateWeddingConfigDtoAgendaInner } from './create-wedding-config-dto-agenda-inner';
import { CreateWeddingConfigDtoHotelsInner } from './create-wedding-config-dto-hotels-inner';


export interface CreateWeddingConfigDto { 
    brideName: string;
    groomName: string;
    tagline: string;
    date: string;
    language: CreateWeddingConfigDtoLanguage;
    themeId: CreateWeddingConfigDto.ThemeIdEnum;
    city: string;
    country: string;
    rsvpDeadline: string;
    venues: Array<CreateWeddingConfigDtoVenuesInner>;
    agenda: Array<CreateWeddingConfigDtoAgendaInner>;
    hotels: Array<CreateWeddingConfigDtoHotelsInner>;
    dietaryPreferences: Array<CreateWeddingConfigDtoDietaryPreferencesInner>;
    allergies: Array<CreateWeddingConfigDtoDietaryPreferencesInner>;
    menus: Array<CreateWeddingConfigDtoMenusInner>;
}
export namespace CreateWeddingConfigDto {
    export const ThemeIdEnum = {
        MAUVE: 'mauve',
        TERRACOTTA: 'terracotta',
        VERDEAGUA: 'verdeagua'
    } as const;
    export type ThemeIdEnum = typeof ThemeIdEnum[keyof typeof ThemeIdEnum];
}


