/**
 * Wedding API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateWeddingConfigDtoVenuesInner { 
    id: string;
    name: string;
    country: string;
    city: string;
    postalCode: string;
    address: string;
    mapUrl: string;
    type: CreateWeddingConfigDtoVenuesInner.TypeEnum;
}
export namespace CreateWeddingConfigDtoVenuesInner {
    export const TypeEnum = {
        CEREMONY: 'ceremony',
        RECEPTION: 'reception',
        OTHER: 'other'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


