/**
 * Wedding API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CreateGuestDtoRelation } from './create-guest-dto-relation';


export interface CreateGuestDto { 
    firstName: string;
    lastName: string;
    email?: string;
    phoneNumber: string;
    preferredLang: CreateGuestDto.PreferredLangEnum;
    delegateTo?: Array<string>;
    relation: CreateGuestDtoRelation;
}
export namespace CreateGuestDto {
    export const PreferredLangEnum = {
        ES: 'es',
        EN: 'en',
        FR: 'fr'
    } as const;
    export type PreferredLangEnum = typeof PreferredLangEnum[keyof typeof PreferredLangEnum];
}


