/**
 * Wedding API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CreateWeddingConfigDtoAgendaItemsInnerTitle } from './create-wedding-config-dto-agenda-items-inner-title';


export interface CreateWeddingConfigDtoAgendaItemsInner { 
    id: string;
    status: CreateWeddingConfigDtoAgendaItemsInner.StatusEnum;
    highlight?: boolean;
    time: string;
    title: CreateWeddingConfigDtoAgendaItemsInnerTitle;
    desc: CreateWeddingConfigDtoAgendaItemsInnerTitle;
    venueId: string | null;
}
export namespace CreateWeddingConfigDtoAgendaItemsInner {
    export const StatusEnum = {
        PLANNED: 'planned',
        CONFIRMED: 'confirmed',
        CANCELLED: 'cancelled'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


