/**
 * Wedding API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CreateWeddingConfigDtoGoodToKnowInnerOneOfNote } from './create-wedding-config-dto-good-to-know-inner-one-of-note';
import { CreateWeddingConfigDtoGoodToKnowInnerOneOfTitle } from './create-wedding-config-dto-good-to-know-inner-one-of-title';


export interface CreateWeddingConfigDtoGoodToKnowInnerOneOf4 { 
    id: string;
    title: CreateWeddingConfigDtoGoodToKnowInnerOneOfTitle;
    type: string;
    rsvpOpen: CreateWeddingConfigDtoGoodToKnowInnerOneOfNote;
    rsvpClosed: CreateWeddingConfigDtoGoodToKnowInnerOneOfNote;
    afterWedding: CreateWeddingConfigDtoGoodToKnowInnerOneOfNote;
}

