/**
 * Wedding API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CreateWeddingConfigDtoGoodToKnowInnerOneOf3 } from './create-wedding-config-dto-good-to-know-inner-one-of3';
import { CreateWeddingConfigDtoGoodToKnowInnerOneOf3EntriesInner } from './create-wedding-config-dto-good-to-know-inner-one-of3-entries-inner';
import { CreateWeddingConfigDtoGoodToKnowInnerOneOf4 } from './create-wedding-config-dto-good-to-know-inner-one-of4';
import { CreateWeddingConfigDtoGoodToKnowInnerOneOf5 } from './create-wedding-config-dto-good-to-know-inner-one-of5';
import { CreateWeddingConfigDtoGoodToKnowInnerOneOfNote } from './create-wedding-config-dto-good-to-know-inner-one-of-note';
import { CreateWeddingConfigDtoGoodToKnowInnerOneOf } from './create-wedding-config-dto-good-to-know-inner-one-of';
import { CreateWeddingConfigDtoGoodToKnowInnerOneOf1 } from './create-wedding-config-dto-good-to-know-inner-one-of1';
import { CreateWeddingConfigDtoGoodToKnowInnerOneOf2 } from './create-wedding-config-dto-good-to-know-inner-one-of2';
import { CreateWeddingConfigDtoGoodToKnowInnerOneOfHeadline } from './create-wedding-config-dto-good-to-know-inner-one-of-headline';
import { CreateWeddingConfigDtoGoodToKnowInnerOneOfBody } from './create-wedding-config-dto-good-to-know-inner-one-of-body';
import { CreateWeddingConfigDtoGoodToKnowInnerOneOfTitle } from './create-wedding-config-dto-good-to-know-inner-one-of-title';


/**
 * @type CreateWeddingConfigDtoGoodToKnowInner
 * @export
 */
export type CreateWeddingConfigDtoGoodToKnowInner = CreateWeddingConfigDtoGoodToKnowInnerOneOf | CreateWeddingConfigDtoGoodToKnowInnerOneOf1 | CreateWeddingConfigDtoGoodToKnowInnerOneOf2 | CreateWeddingConfigDtoGoodToKnowInnerOneOf3 | CreateWeddingConfigDtoGoodToKnowInnerOneOf4 | CreateWeddingConfigDtoGoodToKnowInnerOneOf5;

