/**
 * Wedding API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CreateWeddingConfigDtoGeneralInfoDressCodeHeadline } from './create-wedding-config-dto-general-info-dress-code-headline';


export interface CreateWeddingConfigDtoGeneralInfoContactGuestInner { 
    id: string;
    role: string;
    firstName: string;
    lastName: string;
    email?: string;
    phoneNumber: string;
    purpose: CreateWeddingConfigDtoGeneralInfoDressCodeHeadline;
}

