/**
 * Wedding API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateWeddingConfigDtoHotelsInner { 
    id: string;
    name: string;
    priceTier: CreateWeddingConfigDtoHotelsInner.PriceTierEnum;
    distanceKm: number;
    bookingUrl: string;
    photoKey: string | null;
}
export namespace CreateWeddingConfigDtoHotelsInner {
    export const PriceTierEnum = {
        EURO: '€',
        EURO_EURO: '€€',
        EURO_EURO_EURO: '€€€'
    } as const;
    export type PriceTierEnum = typeof PriceTierEnum[keyof typeof PriceTierEnum];
}


