/**
 * Wedding API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CreateWeddingConfigDtoGeneralInfoGift } from './create-wedding-config-dto-general-info-gift';
import { CreateWeddingConfigDtoGeneralInfoContact } from './create-wedding-config-dto-general-info-contact';
import { CreateWeddingConfigDtoGeneralInfoDressCode } from './create-wedding-config-dto-general-info-dress-code';
import { CreateWeddingConfigDtoGeneralInfoFaqInner } from './create-wedding-config-dto-general-info-faq-inner';
import { CreateWeddingConfigDtoGeneralInfoNoteInner } from './create-wedding-config-dto-general-info-note-inner';
import { CreateWeddingConfigDtoGeneralInfoDayLine } from './create-wedding-config-dto-general-info-day-line';


export interface CreateWeddingConfigDtoGeneralInfo { 
    dressCode?: CreateWeddingConfigDtoGeneralInfoDressCode;
    gift?: CreateWeddingConfigDtoGeneralInfoGift;
    contact?: CreateWeddingConfigDtoGeneralInfoContact;
    faq?: Array<CreateWeddingConfigDtoGeneralInfoFaqInner>;
    dayLine?: CreateWeddingConfigDtoGeneralInfoDayLine;
    note?: Array<CreateWeddingConfigDtoGeneralInfoNoteInner>;
}

