/**
 * Wedding API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CreateWeddingConfigDtoGeneralInfoDressCodeBody } from './create-wedding-config-dto-general-info-dress-code-body';
import { CreateWeddingConfigDtoGeneralInfoDressCodeHeadline } from './create-wedding-config-dto-general-info-dress-code-headline';
import { CreateWeddingConfigDtoGeneralInfoDressCodeNote } from './create-wedding-config-dto-general-info-dress-code-note';


export interface CreateWeddingConfigDtoGeneralInfoGift { 
    intro?: CreateWeddingConfigDtoGeneralInfoDressCodeBody;
    accountHolder?: string;
    iban?: string;
    bic?: string;
    reference?: CreateWeddingConfigDtoGeneralInfoDressCodeHeadline;
    bizumPhone?: string;
    bizumNote?: CreateWeddingConfigDtoGeneralInfoDressCodeNote;
}

