/**
 * Wedding API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CreateWeddingConfigDtoAgendaInnerTitle } from './create-wedding-config-dto-agenda-inner-title';


export interface CreateWeddingConfigDtoDietaryPreferencesInner { 
    id: string;
    label: CreateWeddingConfigDtoAgendaInnerTitle;
    icon?: string;
}

