/**
 * Wedding API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CreateWeddingConfigDtoGoodToKnowInnerOneOf3EntriesInner } from './create-wedding-config-dto-good-to-know-inner-one-of3-entries-inner';
import { CreateWeddingConfigDtoGoodToKnowInnerOneOfTitle } from './create-wedding-config-dto-good-to-know-inner-one-of-title';


export interface CreateWeddingConfigDtoGoodToKnowInnerOneOf3 { 
    id: string;
    title: CreateWeddingConfigDtoGoodToKnowInnerOneOfTitle;
    type: string;
    entries: Array<CreateWeddingConfigDtoGoodToKnowInnerOneOf3EntriesInner>;
}

