/**
 * Wedding API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateRsvpDtoParticipantsInner { 
    id: string;
    type: CreateRsvpDtoParticipantsInner.TypeEnum;
    name: string;
    dietaryPreferenceIds?: Array<string>;
    customDietaryPreferences?: Array<string>;
    allergyIds?: Array<string>;
    customAllergies?: Array<string>;
    menuId?: string | null;
}
export namespace CreateRsvpDtoParticipantsInner {
    export const TypeEnum = {
        MAIN: 'main',
        PARTNER: 'partner',
        CHILD: 'child'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


