/**
 * Wedding API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CreateWeddingConfigDtoGeneralInfoContactGuestInner } from './create-wedding-config-dto-general-info-contact-guest-inner';
import { CreateWeddingConfigDtoGeneralInfoContactWeddingPlannerInner } from './create-wedding-config-dto-general-info-contact-wedding-planner-inner';


export interface CreateWeddingConfigDtoGeneralInfoContact { 
    weddingPlanner?: Array<CreateWeddingConfigDtoGeneralInfoContactWeddingPlannerInner>;
    guest?: Array<CreateWeddingConfigDtoGeneralInfoContactGuestInner>;
}

