/**
 * Wedding API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CreateUserDtoGuestInfo } from './create-user-dto-guest-info';


export interface CreateUserDto { 
    firstName: string;
    lastName: string;
    email?: string;
    googleSub?: string;
    appleSub?: string;
    phoneNumber: string;
    role: CreateUserDto.RoleEnum;
    preferredLang: CreateUserDto.PreferredLangEnum;
    delegateTo?: Array<string>;
    guestInfo?: CreateUserDtoGuestInfo;
}
export namespace CreateUserDto {
    export const RoleEnum = {
        BRIDE: 'bride',
        GROOM: 'groom',
        GUEST: 'guest',
        PROVIDER: 'provider'
    } as const;
    export type RoleEnum = typeof RoleEnum[keyof typeof RoleEnum];
    export const PreferredLangEnum = {
        ES: 'es',
        EN: 'en',
        FR: 'fr'
    } as const;
    export type PreferredLangEnum = typeof PreferredLangEnum[keyof typeof PreferredLangEnum];
}


