/**
 * Wedding API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CreateWeddingConfigDtoGeneralInfoDressCodeBody } from './create-wedding-config-dto-general-info-dress-code-body';
import { CreateWeddingConfigDtoGeneralInfoFaqInnerQuestion } from './create-wedding-config-dto-general-info-faq-inner-question';


export interface CreateWeddingConfigDtoGeneralInfoFaqInner { 
    id: string;
    question: CreateWeddingConfigDtoGeneralInfoFaqInnerQuestion;
    answer: CreateWeddingConfigDtoGeneralInfoDressCodeBody;
}

