/**
 * Wedding API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CreateWeddingConfigDtoGoodToKnowInnerOneOfNote } from './create-wedding-config-dto-good-to-know-inner-one-of-note';
import { CreateWeddingConfigDtoGoodToKnowInnerOneOfHeadline } from './create-wedding-config-dto-good-to-know-inner-one-of-headline';
import { CreateWeddingConfigDtoGoodToKnowInnerOneOfBody } from './create-wedding-config-dto-good-to-know-inner-one-of-body';
import { CreateWeddingConfigDtoGoodToKnowInnerOneOfTitle } from './create-wedding-config-dto-good-to-know-inner-one-of-title';


export interface CreateWeddingConfigDtoGoodToKnowInnerOneOf { 
    id: string;
    title: CreateWeddingConfigDtoGoodToKnowInnerOneOfTitle;
    type: string;
    headline: CreateWeddingConfigDtoGoodToKnowInnerOneOfHeadline;
    body: CreateWeddingConfigDtoGoodToKnowInnerOneOfBody;
    note?: CreateWeddingConfigDtoGoodToKnowInnerOneOfNote;
}

