/**
 * Wedding API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MilestoneListResponseDtoItemsInnerTitle } from './milestone-list-response-dto-items-inner-title';


export interface CreateWeddingConfigDtoDietaryPreferencesInner { 
    id: string;
    label: MilestoneListResponseDtoItemsInnerTitle;
    icon?: string;
}

