/**
 * Wedding API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CreateWeddingConfigDtoGoodToKnowInnerOneOf2EntriesInnerQuestion } from './create-wedding-config-dto-good-to-know-inner-one-of2-entries-inner-question';
import { CreateWeddingConfigDtoGoodToKnowInnerOneOfBody } from './create-wedding-config-dto-good-to-know-inner-one-of-body';


export interface CreateWeddingConfigDtoGoodToKnowInnerOneOf2EntriesInner { 
    id: string;
    question: CreateWeddingConfigDtoGoodToKnowInnerOneOf2EntriesInnerQuestion;
    answer: CreateWeddingConfigDtoGoodToKnowInnerOneOfBody;
}

