/**
 * Wedding API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CreateUserDtoGuestInfoRelationOneOf } from './create-user-dto-guest-info-relation-one-of';
import { CreateUserDtoGuestInfoRelationOneOf1 } from './create-user-dto-guest-info-relation-one-of1';


/**
 * @type CreateUserDtoGuestInfoRelation
 * @export
 */
export type CreateUserDtoGuestInfoRelation = CreateUserDtoGuestInfoRelationOneOf | CreateUserDtoGuestInfoRelationOneOf1;

