/**
 * Wedding API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CreateWeddingConfigDtoAgendaInnerTitle } from './create-wedding-config-dto-agenda-inner-title';


export interface CreateWeddingConfigDtoAgendaInner { 
    id: string;
    time: string;
    title: CreateWeddingConfigDtoAgendaInnerTitle;
    desc: CreateWeddingConfigDtoAgendaInnerTitle;
    venueId: string | null;
}

