/**
 * Wedding API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CreateWeddingConfigDtoGeneralInfoDressCodeBody } from './create-wedding-config-dto-general-info-dress-code-body';
import { CreateWeddingConfigDtoGeneralInfoNoteInnerTitle } from './create-wedding-config-dto-general-info-note-inner-title';


export interface CreateWeddingConfigDtoGeneralInfoNoteInner { 
    id: string;
    title: CreateWeddingConfigDtoGeneralInfoNoteInnerTitle;
    body: CreateWeddingConfigDtoGeneralInfoDressCodeBody;
}

