/**
 * Wedding API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CreateWeddingConfigDtoGoodToKnowInnerOneOfHeadline } from './create-wedding-config-dto-good-to-know-inner-one-of-headline';


export interface CreateWeddingConfigDtoGoodToKnowInnerOneOf3EntriesInner { 
    id: string;
    firstName: string;
    lastName?: string;
    phoneNumber?: string;
    purpose: CreateWeddingConfigDtoGoodToKnowInnerOneOfHeadline;
    userId?: string;
}

