/**
 * Wedding API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GuestListResponseDtoItemsInnerGuestProfileConversationState } from './guest-list-response-dto-items-inner-guest-profile-conversation-state';


export interface CreateGuestDtoGuestProfile { 
    householdId?: string | null;
    delegateFor?: Array<string>;
    notes?: string | null;
    conversationState?: GuestListResponseDtoItemsInnerGuestProfileConversationState | null;
}

