/**
 * Wedding API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateWeddingConfigDtoAgendaInner { 
    id: string;
    time: string;
    title: { [key: string]: string; };
    desc: { [key: string]: string; };
    venueId: string | null;
}

