/**
 * Wedding API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CreateWeddingConfigDtoAgendaInnerTitle } from './create-wedding-config-dto-agenda-inner-title';


export interface CreateWeddingConfigDtoMenusInner { 
    id: string;
    name: CreateWeddingConfigDtoAgendaInnerTitle;
    description: CreateWeddingConfigDtoAgendaInnerTitle;
    suitablePreferenceIds?: Array<string>;
    suitableAllergyIds?: Array<string>;
    active?: boolean;
}

