/**
 * Wedding API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CreateUserDtoGuestInfoRelation } from './create-user-dto-guest-info-relation';


export interface CreateUserDtoGuestInfo { 
    partnerId?: string;
    relation: CreateUserDtoGuestInfoRelation;
}

