/**
 * Wedding API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CreateWeddingConfigDtoGeneralInfoDressCodeNote } from './create-wedding-config-dto-general-info-dress-code-note';


export interface CreateWeddingConfigDtoGeneralInfoDayLine { 
    rsvpOpen: CreateWeddingConfigDtoGeneralInfoDressCodeNote;
    rsvpClosed: CreateWeddingConfigDtoGeneralInfoDressCodeNote;
    afterWedding: CreateWeddingConfigDtoGeneralInfoDressCodeNote;
}

