/**
 * Wedding API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GroomResponseDto { 
    id: string;
    version: number;
    firstName: string;
    lastName: string;
    email?: string;
    nickname?: string;
    googleSub?: string;
    appleSub?: string;
    phoneNumber: string;
    preferredLang: GroomResponseDto.PreferredLangEnum;
}
export namespace GroomResponseDto {
    export const PreferredLangEnum = {
        ES: 'es',
        EN: 'en',
        FR: 'fr'
    } as const;
    export type PreferredLangEnum = typeof PreferredLangEnum[keyof typeof PreferredLangEnum];
}


