/**
 * Wedding API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GuestListResponseDtoItemsInnerRelationOneOf } from './guest-list-response-dto-items-inner-relation-one-of';
import { GuestListResponseDtoItemsInnerRelationOneOf1 } from './guest-list-response-dto-items-inner-relation-one-of1';


/**
 * @type GuestListResponseDtoItemsInnerRelation
 * @export
 */
export type GuestListResponseDtoItemsInnerRelation = GuestListResponseDtoItemsInnerRelationOneOf | GuestListResponseDtoItemsInnerRelationOneOf1;

