/**
 * Wedding API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GuestListResponseDtoItemsInnerRelation } from './guest-list-response-dto-items-inner-relation';


export interface GuestListResponseDtoItemsInner { 
    id: string;
    version: number;
    firstName: string;
    lastName: string;
    email?: string;
    nickname?: string;
    phoneNumber: string;
    role: string;
    preferredLang: GuestListResponseDtoItemsInner.PreferredLangEnum;
    delegateTo?: Array<string>;
    lastSeen?: string;
    partnerId?: string;
    relation: GuestListResponseDtoItemsInnerRelation;
}
export namespace GuestListResponseDtoItemsInner {
    export const PreferredLangEnum = {
        ES: 'es',
        EN: 'en',
        FR: 'fr'
    } as const;
    export type PreferredLangEnum = typeof PreferredLangEnum[keyof typeof PreferredLangEnum];
}


