/**
 * Wedding API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GuestListResponseDtoItemsInner } from './guest-list-response-dto-items-inner';


export interface GuestListResponseDto { 
    items: Array<GuestListResponseDtoItemsInner>;
    nextCursor: string | null;
    count: number;
}

