/**
 * Wedding API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GuestListResponseDtoItemsInnerRelationOneOf1 { 
    side: GuestListResponseDtoItemsInnerRelationOneOf1.SideEnum;
    kind: string;
    link: string;
}
export namespace GuestListResponseDtoItemsInnerRelationOneOf1 {
    export const SideEnum = {
        BRIDE: 'bride',
        GROOM: 'groom',
        BOTH: 'both'
    } as const;
    export type SideEnum = typeof SideEnum[keyof typeof SideEnum];
}


