/**
 * Wedding API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GuestListResponseDtoItemsInnerGuestProfile } from './guest-list-response-dto-items-inner-guest-profile';


export interface GuestListResponseDtoItemsInner { 
    id: string;
    version: number;
    firstName: string;
    lastName: string;
    email?: string;
    googleSub?: string;
    appleSub?: string;
    phoneNumber: string;
    preferredLang?: GuestListResponseDtoItemsInner.PreferredLangEnum;
    guestProfile?: GuestListResponseDtoItemsInnerGuestProfile;
}
export namespace GuestListResponseDtoItemsInner {
    export const PreferredLangEnum = {
        ES: 'es',
        EN: 'en',
        FR: 'fr'
    } as const;
    export type PreferredLangEnum = typeof PreferredLangEnum[keyof typeof PreferredLangEnum];
}


