/**
 * Wedding API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HealthCheckResponseDtoInfoValue } from './health-check-response-dto-info-value';


export interface HealthCheckResponseDto { 
    status: HealthCheckResponseDto.StatusEnum;
    info?: { [key: string]: HealthCheckResponseDtoInfoValue; };
    error?: { [key: string]: HealthCheckResponseDtoInfoValue; };
    details: { [key: string]: HealthCheckResponseDtoInfoValue; };
}
export namespace HealthCheckResponseDto {
    export const StatusEnum = {
        OK: 'ok',
        ERROR: 'error',
        SHUTTING_DOWN: 'shutting_down'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


