/**
 * Wedding API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HealthControllerCheck503ResponseInfoValue } from './health-controller-check503-response-info-value';


export interface HealthControllerCheck503Response { 
    status?: string;
    info?: { [key: string]: HealthControllerCheck503ResponseInfoValue; } | null;
    error?: { [key: string]: HealthControllerCheck503ResponseInfoValue; } | null;
    details?: { [key: string]: HealthControllerCheck503ResponseInfoValue; };
}

