/**
 * Wedding API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ImportGuestDtoGuestsInner } from './import-guest-dto-guests-inner';


export interface ImportGuestDto { 
    guests: Array<ImportGuestDtoGuestsInner>;
}

