/**
 * Wedding API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ImportUserDtoGuestsInnerAnyOf } from './import-user-dto-guests-inner-any-of';
import { ImportUserDtoGuestsInnerAnyOf1 } from './import-user-dto-guests-inner-any-of1';


export interface ImportUserDtoGuestsInner { 
    firstName: string;
    lastName: string;
    phoneNumber: string;
    email?: string;
    role: string;
    delegateTo?: Array<string>;
}

