/**
 * Wedding API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ImportUserDtoGuestsInnerAnyOfRelationOneOf1 } from './import-user-dto-guests-inner-any-of-relation-one-of1';
import { ImportUserDtoGuestsInnerAnyOfRelationOneOf } from './import-user-dto-guests-inner-any-of-relation-one-of';


/**
 * @type ImportUserDtoGuestsInnerAnyOfRelation
 * @export
 */
export type ImportUserDtoGuestsInnerAnyOfRelation = ImportUserDtoGuestsInnerAnyOfRelationOneOf | ImportUserDtoGuestsInnerAnyOfRelationOneOf1;

