/**
 * Wedding API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GuestListResponseDtoItemsInnerRelation } from './guest-list-response-dto-items-inner-relation';


export interface ImportGuestDtoGuestsInner { 
    firstName: string;
    lastName: string;
    phoneNumber: string;
    email?: string;
    delegateTo?: Array<string>;
    relation: GuestListResponseDtoItemsInnerRelation;
    preferredLang: ImportGuestDtoGuestsInner.PreferredLangEnum;
}
export namespace ImportGuestDtoGuestsInner {
    export const PreferredLangEnum = {
        ES: 'es',
        EN: 'en',
        FR: 'fr'
    } as const;
    export type PreferredLangEnum = typeof PreferredLangEnum[keyof typeof PreferredLangEnum];
}


