/**
 * Wedding API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ImportUserDtoGuestsInnerAnyOf1 { 
    firstName: string;
    lastName: string;
    phoneNumber: string;
    email?: string;
    role: string;
}

