/**
 * Wedding API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ImportUserDtoGuestsInnerAnyOfRelationOneOf { 
    side: ImportUserDtoGuestsInnerAnyOfRelationOneOf.SideEnum;
    kind: string;
    link: ImportUserDtoGuestsInnerAnyOfRelationOneOf.LinkEnum;
}
export namespace ImportUserDtoGuestsInnerAnyOfRelationOneOf {
    export const SideEnum = {
        BRIDE: 'bride',
        GROOM: 'groom'
    } as const;
    export type SideEnum = typeof SideEnum[keyof typeof SideEnum];
    export const LinkEnum = {
        AUNT: 'aunt',
        AUNT_IN_LAW: 'aunt-in-law',
        BROTHER: 'brother',
        BROTHER_IN_LAW: 'brother-in-law',
        COUSIN: 'cousin',
        COUSIN_IN_LAW: 'cousin-in-law',
        DAUGHTER: 'daughter',
        FATHER: 'father',
        FATHER_IN_LAW: 'father-in-law',
        GRANDFATHER: 'grandfather',
        GRANDFATHER_IN_LAW: 'grandfather-in-law',
        GRANDMOTHER: 'grandmother',
        GRANDMOTHER_IN_LAW: 'grandmother-in-law',
        MOTHER: 'mother',
        MOTHER_IN_LAW: 'mother-in-law',
        NEPHEW: 'nephew',
        NIECE: 'niece',
        SISTER: 'sister',
        SISTER_IN_LAW: 'sister-in-law',
        SON: 'son',
        STEPAUNT: 'stepaunt',
        STEPBROTHER: 'stepbrother',
        STEPCOUSIN: 'stepcousin',
        STEPDAUGHTER: 'stepdaughter',
        STEPFATHER: 'stepfather',
        STEPGRANDFATHER: 'stepgrandfather',
        STEPGRANDMOTHER: 'stepgrandmother',
        STEPMOTHER: 'stepmother',
        STEPSISTER: 'stepsister',
        STEPSON: 'stepson',
        STEPUNCLE: 'stepuncle',
        UNCLE: 'uncle',
        UNCLE_IN_LAW: 'uncle-in-law'
    } as const;
    export type LinkEnum = typeof LinkEnum[keyof typeof LinkEnum];
}


