/**
 * Wedding API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ImportUserDtoGuestsInnerAnyOfRelation } from './import-user-dto-guests-inner-any-of-relation';


export interface ImportUserDtoGuestsInnerAnyOf { 
    firstName: string;
    lastName: string;
    phoneNumber: string;
    email?: string;
    role: string;
    delegateTo?: Array<string>;
    relation: ImportUserDtoGuestsInnerAnyOfRelation;
}

