/**
 * Wedding API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ImportUserDtoGuestsInner } from './import-user-dto-guests-inner';


export interface ImportUserDto { 
    guests: Array<ImportUserDtoGuestsInner>;
}

