/**
 * Wedding API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MilestoneListResponseDtoItemsInnerAnnouncement } from './milestone-list-response-dto-items-inner-announcement';
import { MilestoneListResponseDtoItemsInnerTitle } from './milestone-list-response-dto-items-inner-title';


export interface MilestoneListResponseDtoItemsInner { 
    id: string;
    title: MilestoneListResponseDtoItemsInnerTitle;
    plannedDate: string;
    kind: MilestoneListResponseDtoItemsInner.KindEnum;
    reached: boolean;
    announcementType?: MilestoneListResponseDtoItemsInner.AnnouncementTypeEnum;
    audience?: MilestoneListResponseDtoItemsInner.AudienceEnum;
    announcement?: MilestoneListResponseDtoItemsInnerAnnouncement;
    version: number;
    atRisk: boolean;
}
export namespace MilestoneListResponseDtoItemsInner {
    export const KindEnum = {
        INTERNAL: 'internal',
        GUEST_FACING: 'guest-facing'
    } as const;
    export type KindEnum = typeof KindEnum[keyof typeof KindEnum];
    export const AnnouncementTypeEnum = {
        SAVE_THE_DATE: 'save-the-date',
        INVITATION: 'invitation',
        RSVP_REMINDER: 'rsvp-reminder',
        MENU_SELECTION_REMINDER: 'menu-selection-reminder'
    } as const;
    export type AnnouncementTypeEnum = typeof AnnouncementTypeEnum[keyof typeof AnnouncementTypeEnum];
    export const AudienceEnum = {
        ALL: 'all',
        NOT_REPLIED: 'not-replied',
        ATTENDING: 'attending',
        ATTENDING_NO_MENU: 'attending-no-menu'
    } as const;
    export type AudienceEnum = typeof AudienceEnum[keyof typeof AudienceEnum];
}


