/**
 * Wedding API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface MilestoneListResponseDtoItemsInnerAnnouncement { 
    sentAt: string;
    sentBy: string;
    announcementType: MilestoneListResponseDtoItemsInnerAnnouncement.AnnouncementTypeEnum;
    audience: MilestoneListResponseDtoItemsInnerAnnouncement.AudienceEnum;
    recipientCount: number;
    reachableCount: number;
}
export namespace MilestoneListResponseDtoItemsInnerAnnouncement {
    export const AnnouncementTypeEnum = {
        SAVE_THE_DATE: 'save-the-date',
        INVITATION: 'invitation',
        RSVP_REMINDER: 'rsvp-reminder',
        MENU_SELECTION_REMINDER: 'menu-selection-reminder'
    } as const;
    export type AnnouncementTypeEnum = typeof AnnouncementTypeEnum[keyof typeof AnnouncementTypeEnum];
    export const AudienceEnum = {
        ALL: 'all',
        NOT_REPLIED: 'not-replied',
        ATTENDING: 'attending',
        ATTENDING_NO_MENU: 'attending-no-menu'
    } as const;
    export type AudienceEnum = typeof AudienceEnum[keyof typeof AudienceEnum];
}


