/**
 * Wedding API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { NotificationListResponseDtoItemsInner } from './notification-list-response-dto-items-inner';


export interface NotificationListResponseDto { 
    items: Array<NotificationListResponseDtoItemsInner>;
    nextCursor: string | null;
    count: number;
}

