/**
 * Wedding API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RsvpDtoAdultsPartner1Options { 
    dietaryPreferenceIds?: Array<string>;
    customDietaryPreferences?: Array<string>;
    allergyIds?: Array<string>;
    customAllergies?: Array<string>;
    menuId?: string | null;
    songRequest?: string | null;
    comments?: string | null;
}

