/**
 * Wedding API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RsvpDtoAdultsGuest } from './rsvp-dto-adults-guest';
import { RsvpDtoAdultsPartner } from './rsvp-dto-adults-partner';


export interface RsvpDtoAdults { 
    guest: RsvpDtoAdultsGuest;
    partner?: RsvpDtoAdultsPartner;
}

