/**
 * Wedding API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RsvpDtoAdults } from './rsvp-dto-adults';
import { RsvpDtoChildrenInner } from './rsvp-dto-children-inner';


export interface RsvpDto { 
    id: string;
    version: number;
    createdAt: string;
    updatedAt: string;
    status: RsvpDto.StatusEnum;
    adults: RsvpDtoAdults;
    children?: Array<RsvpDtoChildrenInner>;
    submittedBy: string;
}
export namespace RsvpDto {
    export const StatusEnum = {
        ATTENDING: 'attending',
        DECLINED: 'declined',
        PENDING: 'pending'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


