/**
 * Wedding API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RsvpDtoAdultsPartner1Options } from './rsvp-dto-adults-partner1-options';


export interface RsvpDtoChildrenInner { 
    firstName: string;
    options?: RsvpDtoAdultsPartner1Options;
    age: number;
}

