/**
 * Wedding API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RsvpDtoAdultsPartner2OneOf1 } from './rsvp-dto-adults-partner2-one-of1';
import { RsvpDtoAdultsPartner1Options } from './rsvp-dto-adults-partner1-options';
import { RsvpDtoAdultsPartner2OneOf } from './rsvp-dto-adults-partner2-one-of';


/**
 * @type RsvpDtoAdultsPartner2
 * @export
 */
export type RsvpDtoAdultsPartner2 = RsvpDtoAdultsPartner2OneOf | RsvpDtoAdultsPartner2OneOf1;

