/**
 * Wedding API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RsvpDtoAdultsGuestOptions } from './rsvp-dto-adults-guest-options';


export interface RsvpDtoAdultsPartnerAnyOf1 { 
    id: string;
    firstName: string;
    lastName: string;
    options?: RsvpDtoAdultsGuestOptions;
}

