/**
 * Wedding API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RsvpListResponseDtoItemsInnerAdults } from './rsvp-list-response-dto-items-inner-adults';
import { RsvpDtoChildrenInner } from './rsvp-dto-children-inner';


export interface RsvpListResponseDtoItemsInner { 
    id: string;
    version: number;
    createdAt: string;
    updatedAt: string;
    status: RsvpListResponseDtoItemsInner.StatusEnum;
    adults: RsvpListResponseDtoItemsInnerAdults;
    children?: Array<RsvpDtoChildrenInner>;
    submittedBy: string;
    delegatedTo?: string;
}
export namespace RsvpListResponseDtoItemsInner {
    export const StatusEnum = {
        YES: 'yes',
        NO: 'no',
        PENDING: 'pending'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


