/**
 * Wedding API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RsvpReportResponseDtoRowsInner } from './rsvp-report-response-dto-rows-inner';
import { RsvpReportResponseDtoCounts } from './rsvp-report-response-dto-counts';


export interface RsvpReportResponseDto { 
    rows: Array<RsvpReportResponseDtoRowsInner>;
    counts: RsvpReportResponseDtoCounts;
}

