/**
 * Wedding API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RsvpListResponseDtoItemsInner } from './rsvp-list-response-dto-items-inner';


export interface RsvpListResponseDto { 
    items: Array<RsvpListResponseDtoItemsInner>;
    nextCursor: string | null;
    count: number;
}

