/**
 * Wedding API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RsvpReportResponseDtoRowsInnerRsvp } from './rsvp-report-response-dto-rows-inner-rsvp';
import { GuestListResponseDtoItemsInner } from './guest-list-response-dto-items-inner';


export interface RsvpReportResponseDtoRowsInner { 
    guest: GuestListResponseDtoItemsInner;
    rsvp: RsvpReportResponseDtoRowsInnerRsvp | null;
    rsvpStatus: RsvpReportResponseDtoRowsInner.RsvpStatusEnum;
}
export namespace RsvpReportResponseDtoRowsInner {
    export const RsvpStatusEnum = {
        YES: 'yes',
        NO: 'no',
        PENDING: 'pending'
    } as const;
    export type RsvpStatusEnum = typeof RsvpStatusEnum[keyof typeof RsvpStatusEnum];
}


