/**
 * Wedding API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RsvpDtoAdultsPartnerAnyOf1 } from './rsvp-dto-adults-partner-any-of1';
import { RsvpDtoAdultsGuestOptions } from './rsvp-dto-adults-guest-options';
import { RsvpDtoAdultsPartnerAnyOf } from './rsvp-dto-adults-partner-any-of';


export interface RsvpDtoAdultsPartner { 
    firstName: string;
    lastName: string;
    options?: RsvpDtoAdultsGuestOptions;
    id: string;
}

