/**
 * Wedding API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RsvpDtoAdultsPartner1 } from './rsvp-dto-adults-partner1';
import { RsvpDtoAdultsPartner1Options } from './rsvp-dto-adults-partner1-options';
import { RsvpDtoAdultsPartner2AnyOf } from './rsvp-dto-adults-partner2-any-of';


export interface RsvpDtoAdultsPartner2 { 
    firstName: string;
    lastName: string;
    options?: RsvpDtoAdultsPartner1Options;
    id: string;
}

