/**
 * Wedding API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RsvpDtoAdultsPartner2 } from './rsvp-dto-adults-partner2';
import { RsvpDtoAdultsPartner1 } from './rsvp-dto-adults-partner1';


export interface RsvpListResponseDtoItemsInnerAdults { 
    partner1: RsvpDtoAdultsPartner1;
    partner2?: RsvpDtoAdultsPartner2;
}

