/**
 * Wedding API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CreateRsvpDtoParticipantsInner } from './create-rsvp-dto-participants-inner';


export interface RsvpDto { 
    id: string;
    version: number;
    createdAt: string;
    updatedAt: string;
    status: RsvpDto.StatusEnum;
    participants: Array<CreateRsvpDtoParticipantsInner>;
    songRequest?: string | null;
    comments?: string | null;
    submittedBy: string;
}
export namespace RsvpDto {
    export const StatusEnum = {
        YES: 'yes',
        NO: 'no',
        PENDING: 'pending'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


