/**
 * Wedding API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RsvpDtoAdults } from './rsvp-dto-adults';
import { RsvpDtoAdultsPartner2AnyOf } from './rsvp-dto-adults-partner2-any-of';


export interface RsvpDto { 
    id: string;
    version: number;
    createdAt: string;
    updatedAt: string;
    status: RsvpDto.StatusEnum;
    adults: RsvpDtoAdults;
    children?: Array<RsvpDtoAdultsPartner2AnyOf>;
    submittedBy: string;
}
export namespace RsvpDto {
    export const StatusEnum = {
        ATTENDING: 'attending',
        DECLINED: 'declined',
        PENDING: 'pending'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


