/**
 * Wedding API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SocialLoginDto { 
    provider: SocialLoginDto.ProviderEnum;
    idToken: string;
}
export namespace SocialLoginDto {
    export const ProviderEnum = {
        GOOGLE: 'google',
        APPLE: 'apple'
    } as const;
    export type ProviderEnum = typeof ProviderEnum[keyof typeof ProviderEnum];
}


