/**
 * Wedding API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SubmitRsvpDto { 
    attending: boolean;
    bringingPartner?: boolean;
    childrenCount?: number;
    dietaryNotes?: string | null;
    songRequest?: string | null;
    comments?: string | null;
}

