/**
 * Wedding API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RsvpDtoChildrenInner } from './rsvp-dto-children-inner';
import { UpdateRsvpDtoAdults } from './update-rsvp-dto-adults';


export interface UpdateRsvpDto { 
    id: string;
    version: number;
    status?: UpdateRsvpDto.StatusEnum;
    adults?: UpdateRsvpDtoAdults;
    children?: Array<RsvpDtoChildrenInner>;
    delegatedTo?: string;
}
export namespace UpdateRsvpDto {
    export const StatusEnum = {
        ATTENDING: 'attending',
        DECLINED: 'declined',
        PENDING: 'pending'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


