/**
 * Wedding API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UpdateBrideDto { 
    id: string;
    version: number;
    firstName?: string;
    lastName?: string;
    googleSub?: string;
    appleSub?: string;
    preferredLang?: UpdateBrideDto.PreferredLangEnum;
}
export namespace UpdateBrideDto {
    export const PreferredLangEnum = {
        ES: 'es',
        EN: 'en',
        FR: 'fr'
    } as const;
    export type PreferredLangEnum = typeof PreferredLangEnum[keyof typeof PreferredLangEnum];
}


