/**
 * Wedding API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CreateGuestDtoRelation } from './create-guest-dto-relation';
import { UserListResponseDtoItemsInnerDelegateToInner } from './user-list-response-dto-items-inner-delegate-to-inner';


export interface UpdateGuestDto { 
    firstName?: string;
    lastName?: string;
    nickname?: string;
    preferredLang?: UpdateGuestDto.PreferredLangEnum;
    delegateTo?: Array<UserListResponseDtoItemsInnerDelegateToInner>;
    relation?: CreateGuestDtoRelation;
    id: string;
    version: number;
}
export namespace UpdateGuestDto {
    export const PreferredLangEnum = {
        ES: 'es',
        EN: 'en',
        FR: 'fr'
    } as const;
    export type PreferredLangEnum = typeof PreferredLangEnum[keyof typeof PreferredLangEnum];
}


