/**
 * Wedding API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CreateWeddingConfigDtoVenuesInner } from './create-wedding-config-dto-venues-inner';
import { CreateWeddingConfigDtoDietaryPreferencesInner } from './create-wedding-config-dto-dietary-preferences-inner';
import { CreateWeddingConfigDtoMenusInner } from './create-wedding-config-dto-menus-inner';
import { UpdateMilestoneDtoTitle } from './update-milestone-dto-title';
import { UpdateWeddingConfigDtoAgenda } from './update-wedding-config-dto-agenda';
import { CreateWeddingConfigDtoHotelsInner } from './create-wedding-config-dto-hotels-inner';


export interface UpdateWeddingConfigDto { 
    version: number;
    brideName?: string;
    groomName?: string;
    tagline?: string;
    date?: string;
    language?: UpdateMilestoneDtoTitle;
    themeId?: UpdateWeddingConfigDto.ThemeIdEnum;
    city?: string;
    country?: string;
    rsvpDeadline?: string;
    venues?: Array<CreateWeddingConfigDtoVenuesInner>;
    agenda?: UpdateWeddingConfigDtoAgenda;
    hotels?: Array<CreateWeddingConfigDtoHotelsInner>;
    dietaryPreferences?: Array<CreateWeddingConfigDtoDietaryPreferencesInner>;
    allergies?: Array<CreateWeddingConfigDtoDietaryPreferencesInner>;
    menus?: Array<CreateWeddingConfigDtoMenusInner>;
}
export namespace UpdateWeddingConfigDto {
    export const ThemeIdEnum = {
        MAUVE: 'mauve',
        TERRACOTTA: 'terracotta',
        VERDEAGUA: 'verdeagua'
    } as const;
    export type ThemeIdEnum = typeof ThemeIdEnum[keyof typeof ThemeIdEnum];
}


