/**
 * Wedding API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CreateWeddingConfigDtoVenuesInner } from './create-wedding-config-dto-venues-inner';
import { CreateWeddingConfigDtoAgendaInner } from './create-wedding-config-dto-agenda-inner';
import { CreateWeddingConfigDtoHotelsInner } from './create-wedding-config-dto-hotels-inner';


export interface UpdateWeddingConfigDto { 
    id: string;
    version: number;
    createdAt?: string;
    updatedAt?: string;
    brideName?: string;
    groomName?: string;
    tagline?: string;
    date?: string;
    language?: { [key: string]: string; };
    themeId?: UpdateWeddingConfigDto.ThemeIdEnum;
    city?: string;
    country?: string;
    rsvpDeadline?: string;
    venues?: Array<CreateWeddingConfigDtoVenuesInner>;
    agenda?: Array<CreateWeddingConfigDtoAgendaInner>;
    hotels?: Array<CreateWeddingConfigDtoHotelsInner>;
}
export namespace UpdateWeddingConfigDto {
    export const ThemeIdEnum = {
        MAUVE: 'mauve',
        TERRACOTTA: 'terracotta',
        VERDEAGUA: 'verdeagua'
    } as const;
    export type ThemeIdEnum = typeof ThemeIdEnum[keyof typeof ThemeIdEnum];
}


