/**
 * Wedding API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CreateWeddingConfigDtoAgendaItemsInner } from './create-wedding-config-dto-agenda-items-inner';


export interface UpdateWeddingConfigDtoAgenda { 
    status: UpdateWeddingConfigDtoAgenda.StatusEnum;
    items: Array<CreateWeddingConfigDtoAgendaItemsInner>;
}
export namespace UpdateWeddingConfigDtoAgenda {
    export const StatusEnum = {
        PROVISIONAL: 'provisional',
        FINAL: 'final'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


