/**
 * Wedding API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UpdateGuestDto { 
    id: string;
    firstName?: string;
    lastName?: string;
    preferredLang?: UpdateGuestDto.PreferredLangEnum;
    householdId?: string | null;
    delegateFor?: Array<string>;
    notes?: string | null;
}
export namespace UpdateGuestDto {
    export const PreferredLangEnum = {
        ES: 'es',
        EN: 'en',
        FR: 'fr'
    } as const;
    export type PreferredLangEnum = typeof PreferredLangEnum[keyof typeof PreferredLangEnum];
}


