/**
 * Wedding API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserListResponseDtoItemsInnerDelegateToInner } from './user-list-response-dto-items-inner-delegate-to-inner';


export interface UpdateUserDto { 
    id: string;
    version: number;
    firstName?: string;
    lastName?: string;
    nickname?: string;
    googleSub?: string;
    appleSub?: string;
    preferredLang?: UpdateUserDto.PreferredLangEnum;
    delegateTo?: Array<UserListResponseDtoItemsInnerDelegateToInner>;
}
export namespace UpdateUserDto {
    export const PreferredLangEnum = {
        ES: 'es',
        EN: 'en',
        FR: 'fr'
    } as const;
    export type PreferredLangEnum = typeof PreferredLangEnum[keyof typeof PreferredLangEnum];
}


