/**
 * Wedding API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UpdateSettingsDtoNotificationPrefs } from './update-settings-dto-notification-prefs';


export interface UpdateSettingsDto { 
    notificationPrefs?: UpdateSettingsDtoNotificationPrefs;
}

