/**
 * Wedding API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UpdateMilestoneDtoTitle } from './update-milestone-dto-title';


export interface UpdateMilestoneDto { 
    title?: UpdateMilestoneDtoTitle;
    plannedDate?: string;
    reached?: boolean;
    announcementType?: UpdateMilestoneDto.AnnouncementTypeEnum;
    audience?: UpdateMilestoneDto.AudienceEnum;
    version: number;
}
export namespace UpdateMilestoneDto {
    export const AnnouncementTypeEnum = {
        SAVE_THE_DATE: 'save-the-date',
        INVITATION: 'invitation',
        RSVP_REMINDER: 'rsvp-reminder',
        MENU_SELECTION_REMINDER: 'menu-selection-reminder'
    } as const;
    export type AnnouncementTypeEnum = typeof AnnouncementTypeEnum[keyof typeof AnnouncementTypeEnum];
    export const AudienceEnum = {
        ALL: 'all',
        NOT_REPLIED: 'not-replied',
        ATTENDING: 'attending',
        ATTENDING_NO_MENU: 'attending-no-menu'
    } as const;
    export type AudienceEnum = typeof AudienceEnum[keyof typeof AudienceEnum];
}


