/**
 * Wedding API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UserProfileListResponseDtoProfilesInnerGuestInfoPartnerAnyOf1 { 
    firstName: string;
    lastName: string;
    nickname?: string;
    kind: string;
}

