/**
 * Wedding API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserProfileListResponseDtoProfilesInnerGuestInfoRsvp } from './user-profile-list-response-dto-profiles-inner-guest-info-rsvp';
import { CreateUserDtoGuestInfoRelation } from './create-user-dto-guest-info-relation';
import { UserProfileListResponseDtoProfilesInnerGuestInfoPartner } from './user-profile-list-response-dto-profiles-inner-guest-info-partner';


export interface UserProfileListResponseDtoProfilesInnerGuestInfo { 
    relation: CreateUserDtoGuestInfoRelation;
    partner?: UserProfileListResponseDtoProfilesInnerGuestInfoPartner;
    rsvp?: UserProfileListResponseDtoProfilesInnerGuestInfoRsvp;
}

