/**
 * Wedding API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserProfileListResponseDtoItemsInnerGuestInfoPartnerAnyOf } from './user-profile-list-response-dto-items-inner-guest-info-partner-any-of';
import { UserProfileListResponseDtoItemsInnerGuestInfoPartnerAnyOf1 } from './user-profile-list-response-dto-items-inner-guest-info-partner-any-of1';


export interface UserProfileListResponseDtoItemsInnerGuestInfoPartner { 
    id: string;
    firstName: string;
    lastName: string;
    nickname?: string;
    kind: string;
    attending: boolean;
}

