/**
 * Wedding API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ImportUserDtoGuestsInnerAnyOfRelation } from './import-user-dto-guests-inner-any-of-relation';


export interface UserProfileListResponseDtoProfilesInner { 
    id: string;
    firstName: string;
    lastName: string;
    email?: string;
    phoneNumber?: string;
    preferredLang?: UserProfileListResponseDtoProfilesInner.PreferredLangEnum;
    role: UserProfileListResponseDtoProfilesInner.RoleEnum;
    relation?: ImportUserDtoGuestsInnerAnyOfRelation;
}
export namespace UserProfileListResponseDtoProfilesInner {
    export const PreferredLangEnum = {
        ES: 'es',
        EN: 'en',
        FR: 'fr'
    } as const;
    export type PreferredLangEnum = typeof PreferredLangEnum[keyof typeof PreferredLangEnum];
    export const RoleEnum = {
        BRIDE: 'bride',
        GROOM: 'groom',
        GUEST: 'guest',
        PROVIDER: 'provider'
    } as const;
    export type RoleEnum = typeof RoleEnum[keyof typeof RoleEnum];
}


