/**
 * Wedding API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UserProfileListResponseDtoProfilesInner { 
    id: string;
    firstName: string;
    lastName: string;
    email?: string;
    phoneNumber: string;
    preferredLang?: UserProfileListResponseDtoProfilesInner.PreferredLangEnum;
}
export namespace UserProfileListResponseDtoProfilesInner {
    export const PreferredLangEnum = {
        ES: 'es',
        EN: 'en',
        FR: 'fr'
    } as const;
    export type PreferredLangEnum = typeof PreferredLangEnum[keyof typeof PreferredLangEnum];
}


