/**
 * Wedding API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserProfileListResponseDtoProfilesInner } from './user-profile-list-response-dto-profiles-inner';


export interface UserProfileListResponseDto { 
    profiles: Array<UserProfileListResponseDtoProfilesInner>;
    notFoundIds?: Array<string>;
}

