/**
 * Wedding API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UserProfileListResponseDtoProfilesInnerGuestInfoPartnerAnyOf { 
    firstName: string;
    lastName: string;
    kind: UserProfileListResponseDtoProfilesInnerGuestInfoPartnerAnyOf.KindEnum;
}
export namespace UserProfileListResponseDtoProfilesInnerGuestInfoPartnerAnyOf {
    export const KindEnum = {
        GUEST: 'guest',
        PLUS_ONE: 'plus-one',
        CHILD: 'child'
    } as const;
    export type KindEnum = typeof KindEnum[keyof typeof KindEnum];
}


