/**
 * Wedding API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UserProfileListResponseDtoItemsInnerGuestInfoRsvp { 
    id: string;
    status: UserProfileListResponseDtoItemsInnerGuestInfoRsvp.StatusEnum;
    adults: number;
    children?: number;
}
export namespace UserProfileListResponseDtoItemsInnerGuestInfoRsvp {
    export const StatusEnum = {
        ATTENDING: 'attending',
        DECLINED: 'declined',
        PENDING: 'pending'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


