/**
 * Wedding API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserProfileDtoGuestInfo } from './user-profile-dto-guest-info';


export interface UserProfileDto { 
    id: string;
    firstName: string;
    lastName: string;
    email?: string;
    phoneNumber?: string;
    preferredLang: UserProfileDto.PreferredLangEnum;
    role: UserProfileDto.RoleEnum;
    lastSeen?: string;
    guestInfo?: UserProfileDtoGuestInfo;
}
export namespace UserProfileDto {
    export const PreferredLangEnum = {
        ES: 'es',
        EN: 'en',
        FR: 'fr'
    } as const;
    export type PreferredLangEnum = typeof PreferredLangEnum[keyof typeof PreferredLangEnum];
    export const RoleEnum = {
        BRIDE: 'bride',
        GROOM: 'groom',
        GUEST: 'guest',
        PROVIDER: 'provider'
    } as const;
    export type RoleEnum = typeof RoleEnum[keyof typeof RoleEnum];
}


