/**
 * Wedding API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UserProfileListResponseDtoItemsInnerGuestInfoPartnerAnyOf { 
    id: string;
    firstName: string;
    lastName: string;
    nickname?: string;
    kind: string;
    attending?: boolean;
}

