/**
 * Wedding API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserProfileListResponseDtoProfilesInnerGuestInfoRsvp } from './user-profile-list-response-dto-profiles-inner-guest-info-rsvp';
import { GuestListResponseDtoItemsInnerRelation } from './guest-list-response-dto-items-inner-relation';
import { UserProfileListResponseDtoProfilesInnerGuestInfoPartner } from './user-profile-list-response-dto-profiles-inner-guest-info-partner';


export interface UserProfileDtoGuestInfo { 
    relation: GuestListResponseDtoItemsInnerRelation;
    partner?: UserProfileListResponseDtoProfilesInnerGuestInfoPartner;
    rsvp?: UserProfileListResponseDtoProfilesInnerGuestInfoRsvp;
}

