/**
 * Wedding API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserProfileListResponseDtoItemsInner } from './user-profile-list-response-dto-items-inner';


export interface UserProfileListResponseDto { 
    items: Array<UserProfileListResponseDtoItemsInner>;
    nextCursor: string | null;
    count: number;
    notFoundIds?: Array<string>;
    /**
     * Deprecated alias of `items`, populated with the same array. Read `items`; this field is removed in a later release.
     */
    profiles: Array<UserProfileListResponseDtoItemsInner>;
}

