/**
 * Wedding API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserProfileListResponseDtoItemsInnerGuestInfoRsvp } from './user-profile-list-response-dto-items-inner-guest-info-rsvp';
import { UserProfileListResponseDtoItemsInnerGuestInfoPartner } from './user-profile-list-response-dto-items-inner-guest-info-partner';
import { GuestListResponseDtoItemsInnerRelation } from './guest-list-response-dto-items-inner-relation';


export interface UserProfileListResponseDtoItemsInnerGuestInfo { 
    relation: GuestListResponseDtoItemsInnerRelation;
    partner?: UserProfileListResponseDtoItemsInnerGuestInfoPartner;
    rsvp?: UserProfileListResponseDtoItemsInnerGuestInfoRsvp;
}

