/**
 * Wedding API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserListResponseDtoItemsInnerDelegateToInner } from './user-list-response-dto-items-inner-delegate-to-inner';
import { UserProfileListResponseDtoItemsInnerGuestInfo } from './user-profile-list-response-dto-items-inner-guest-info';


export interface UserProfileListResponseDtoItemsInner { 
    id: string;
    firstName: string;
    lastName: string;
    nickname?: string;
    email?: string;
    phoneNumber?: string;
    preferredLang: UserProfileListResponseDtoItemsInner.PreferredLangEnum;
    role: UserProfileListResponseDtoItemsInner.RoleEnum;
    lastSeen?: string;
    delegateTo?: Array<UserListResponseDtoItemsInnerDelegateToInner>;
    guestInfo?: UserProfileListResponseDtoItemsInnerGuestInfo;
}
export namespace UserProfileListResponseDtoItemsInner {
    export const PreferredLangEnum = {
        ES: 'es',
        EN: 'en',
        FR: 'fr'
    } as const;
    export type PreferredLangEnum = typeof PreferredLangEnum[keyof typeof PreferredLangEnum];
    export const RoleEnum = {
        BRIDE: 'bride',
        GROOM: 'groom',
        GUEST: 'guest',
        PROVIDER: 'provider'
    } as const;
    export type RoleEnum = typeof RoleEnum[keyof typeof RoleEnum];
}


