/**
 * Wedding API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UserListResponseDtoItemsInnerDelegateToInner { 
    id: string;
    kind: UserListResponseDtoItemsInnerDelegateToInner.KindEnum;
}
export namespace UserListResponseDtoItemsInnerDelegateToInner {
    export const KindEnum = {
        FATHER: 'father',
        MOTHER: 'mother',
        BROTHER: 'brother',
        SISTER: 'sister'
    } as const;
    export type KindEnum = typeof KindEnum[keyof typeof KindEnum];
}


