/**
 * Wedding API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ImportUserDtoGuestsInnerAnyOfRelation } from './import-user-dto-guests-inner-any-of-relation';
import { UserProfileListResponseDtoProfilesInnerGuestInfoRsvp } from './user-profile-list-response-dto-profiles-inner-guest-info-rsvp';
import { UserProfileListResponseDtoProfilesInnerGuestInfoPartner } from './user-profile-list-response-dto-profiles-inner-guest-info-partner';


export interface UserProfileDtoGuestInfo { 
    relation: ImportUserDtoGuestsInnerAnyOfRelation;
    partner?: UserProfileListResponseDtoProfilesInnerGuestInfoPartner;
    rsvp?: UserProfileListResponseDtoProfilesInnerGuestInfoRsvp;
}

