/**
 * Wedding API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserProfileListResponseDtoProfilesInnerGuestInfoPartnerAnyOf1 } from './user-profile-list-response-dto-profiles-inner-guest-info-partner-any-of1';
import { UserProfileListResponseDtoProfilesInnerGuestInfoPartnerAnyOf } from './user-profile-list-response-dto-profiles-inner-guest-info-partner-any-of';


export interface UserProfileListResponseDtoProfilesInnerGuestInfoPartner { 
    firstName: string;
    lastName: string;
    id: string;
    attending?: boolean;
}

