/**
 * Wedding API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { WeddingGeneralInformationDtoGift } from './wedding-general-information-dto-gift';
import { WeddingGeneralInformationDtoContact } from './wedding-general-information-dto-contact';
import { CreateWeddingConfigDtoGeneralInfoFaqInner } from './create-wedding-config-dto-general-info-faq-inner';
import { CreateWeddingConfigDtoGeneralInfoNoteInner } from './create-wedding-config-dto-general-info-note-inner';
import { WeddingGeneralInformationDtoDressCode } from './wedding-general-information-dto-dress-code';
import { WeddingGeneralInformationDtoDayLine } from './wedding-general-information-dto-day-line';


export interface WeddingGeneralInformationDto { 
    dressCode?: WeddingGeneralInformationDtoDressCode;
    gift?: WeddingGeneralInformationDtoGift;
    contact: WeddingGeneralInformationDtoContact;
    faq?: Array<CreateWeddingConfigDtoGeneralInfoFaqInner>;
    dayLine?: WeddingGeneralInformationDtoDayLine;
    note?: Array<CreateWeddingConfigDtoGeneralInfoNoteInner>;
}

