/**
 * Wedding API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { WeddingConfigPublicResponseDtoSocialProviders } from './wedding-config-public-response-dto-social-providers';
import { WeddingConfigPublicResponseDtoLanguage } from './wedding-config-public-response-dto-language';
import { WeddingConfigPublicResponseDtoMainVenue } from './wedding-config-public-response-dto-main-venue';


export interface WeddingConfigPublicResponseDto { 
    id: string;
    brideName: string;
    groomName: string;
    tagline: string;
    date: string;
    language: WeddingConfigPublicResponseDtoLanguage;
    themeId: WeddingConfigPublicResponseDto.ThemeIdEnum;
    city: string;
    country: string;
    rsvpDeadline: string;
    mainVenue: WeddingConfigPublicResponseDtoMainVenue;
    socialProviders?: WeddingConfigPublicResponseDtoSocialProviders;
}
export namespace WeddingConfigPublicResponseDto {
    export const ThemeIdEnum = {
        MAUVE: 'mauve',
        TERRACOTTA: 'terracotta',
        VERDEAGUA: 'verdeagua'
    } as const;
    export type ThemeIdEnum = typeof ThemeIdEnum[keyof typeof ThemeIdEnum];
}


