/**
 * Wedding API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CreateWeddingConfigDtoVenuesInner } from './create-wedding-config-dto-venues-inner';
import { CreateWeddingConfigDtoDietaryPreferencesInner } from './create-wedding-config-dto-dietary-preferences-inner';
import { CreateWeddingConfigDtoMenusInner } from './create-wedding-config-dto-menus-inner';
import { MilestoneDtoTitle } from './milestone-dto-title';
import { CreateWeddingConfigDtoAgenda } from './create-wedding-config-dto-agenda';
import { CreateWeddingConfigDtoHotelsInner } from './create-wedding-config-dto-hotels-inner';


export interface WeddingConfigResponseDto { 
    id: string;
    version: number;
    brideName: string;
    groomName: string;
    tagline: string;
    date: string;
    language: MilestoneDtoTitle;
    themeId: WeddingConfigResponseDto.ThemeIdEnum;
    city: string;
    country: string;
    rsvpDeadline: string;
    venues: Array<CreateWeddingConfigDtoVenuesInner>;
    agenda: CreateWeddingConfigDtoAgenda;
    hotels: Array<CreateWeddingConfigDtoHotelsInner>;
    dietaryPreferences: Array<CreateWeddingConfigDtoDietaryPreferencesInner>;
    allergies: Array<CreateWeddingConfigDtoDietaryPreferencesInner>;
    menus: Array<CreateWeddingConfigDtoMenusInner>;
}
export namespace WeddingConfigResponseDto {
    export const ThemeIdEnum = {
        MAUVE: 'mauve',
        TERRACOTTA: 'terracotta',
        VERDEAGUA: 'verdeagua'
    } as const;
    export type ThemeIdEnum = typeof ThemeIdEnum[keyof typeof ThemeIdEnum];
}


