/**
 * Wedding API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { WeddingGeneralInformationDtoContactCoupleBride } from './wedding-general-information-dto-contact-couple-bride';


export interface WeddingGeneralInformationDtoContactCouple { 
    bride: WeddingGeneralInformationDtoContactCoupleBride;
    groom: WeddingGeneralInformationDtoContactCoupleBride;
}

